---
# Check if Docker is installed and running

- name: Check if Docker is installed
  ansible.builtin.command: which docker
  register: docker_check
  changed_when: false
  failed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed. Please install Docker first."
  when: docker_check.rc != 0

- name: Check if Docker is running
  ansible.builtin.command: docker info
  register: docker_running
  changed_when: false
  failed_when: false

- name: Fail if Docker is not running
  ansible.builtin.fail:
    msg: "Docker is not running. Please start Docker service."
  when: docker_running.rc != 0

- name: Check if Docker Compose plugin is available
  ansible.builtin.command: docker compose version
  register: compose_check
  changed_when: false
  failed_when: false

- name: Fail if Docker Compose plugin is not available
  ansible.builtin.fail:
    msg: "Docker Compose plugin is not available. Please install Docker Compose plugin."
  when: compose_check.rc != 0
