---
# Homepage Role Tasks

- name: Create Homepage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/opt/docker/homepage"
    - "/opt/docker/homepage/config"

- name: Copy Homepage configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/opt/docker/homepage/config/{{ item }}"
    mode: '0644'
  with_items:
    - "settings.yaml"
    - "bookmarks.yaml"
    - "services.yaml"
    - "widgets.yaml"
    - "docker.yaml"

- name: Stop and remove existing Homepage container if exists
  community.docker.docker_container:
    name: homepage
    state: absent
    force_kill: yes

- name: Check if Docker network exists
  shell: docker network ls | grep {{ homepage_docker_network }}
  register: network_check
  changed_when: false
  failed_when: false

- name: Create Docker network if it doesn't exist
  community.docker.docker_network:
    name: "{{ homepage_docker_network }}"
    driver: bridge
  when: network_check.rc != 0

- name: Deploy Homepage container
  community.docker.docker_container:
    name: homepage
    image: "{{ homepage_image }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ homepage_docker_network }}"
    volumes:
      - "/opt/docker/homepage/config:/app/config"
    env:
      DOCKER_HOST: "{{ homepage_docker_socket }}"
      TZ: "UTC"
      HOMEPAGE_CONFIG_DIR: "/app/config"
      HOMEPAGE_DOCKER_ENABLE: "true"
      HOMEPAGE_DOCKER_REFRESH_INTERVAL: "{{ homepage_docker_refresh_interval | default(300) }}"
      HOMEPAGE_ALLOWED_HOSTS: "{{ homepage_domain }},{{ vault_service_domains.homepage }},*.{{ vault_domain }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`{{ homepage_domain }}`)"
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.tls.certresolver: "cloudflare"
      traefik.http.services.homepage.loadbalancer.server.port: "{{ homepage_port }}"
      traefik.http.routers.homepage.middlewares: "security-headers@file"
      # Homepage-specific labels for service discovery
      homepage.enable: "true"
      homepage.name: "Homepage"
      homepage.icon: "si-homepage"
      homepage.description: "Homepage Dashboard"
      homepage.href: "https://{{ homepage_domain }}"
      homepage.group: "{{ inventory_hostname }}"
      # Watchtower Update Control
      com.centurylinklabs.watchtower.enable: "true"
      