---
# Portainer Agent Deployment Tasks
# This file is managed by Ansible - local changes will be overwritten

- name: Create Portainer Agent directories
  file:
    path: "/opt/docker/portainer-agent"
    state: directory
    mode: '0755'

- name: Stop and remove existing Portainer Agent container if exists
  community.docker.docker_container:
    name: "{{ portainer_agent_container_name }}"
    state: absent
    force_kill: yes

- name: Check if Docker network exists
  shell: docker network ls | grep {{ portainer_agent_docker_network }}
  register: network_check
  changed_when: false
  failed_when: false

- name: Create Docker network if it doesn't exist
  community.docker.docker_network:
    name: "{{ portainer_agent_docker_network }}"
    driver: bridge
  when: network_check.rc != 0

- name: Deploy Portainer Agent container
  community.docker.docker_container:
    name: "{{ portainer_agent_container_name }}"
    image: "{{ portainer_agent_image }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ portainer_agent_docker_network }}"
    ports:
      - "{{ portainer_agent_port }}:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes:ro"
    env:
      AGENT_CLUSTER_ADDR: "{{ ansible_default_ipv4.address }}"
      TZ: "UTC"
    labels:
      # Homepage-specific labels
      homepage.enable: "true"
      homepage.name: "Portainer Agent ({{ inventory_hostname }})"
      homepage.icon: "si-portainer"
      homepage.description: "Container Management Agent"
      homepage.href: "https://{{ vault_service_domains.portainer }}/#/endpoints"
      homepage.group: "{{ inventory_hostname }}"
      homepage.statusStyle: ""
      # Watchtower Update Control
      com.centurylinklabs.watchtower.enable: "true"
