---
# Portainer Agent defaults

# Container configuration
portainer_agent_image: "portainer/agent:latest"
portainer_agent_container_name: "portainer-agent"
portainer_agent_port: 9001

# Network configuration
portainer_agent_docker_network: "traefik-net"

# Labels
portainer_agent_group: "Infrastructure"
