---
# Docker installation tasks for ARM architecture (Raspberry Pi)

- name: Add Docker GPG key for ARM
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker APT repository for ARM
  become: true
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == 'Debian'

- name: Install Docker packages on ARM
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
